/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiAuthCheckPost201ResponsePermissions type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiAuthCheckPost201ResponsePermissions{}

// ApiAuthCheckPost201ResponsePermissions List of permissions acquired
type ApiAuthCheckPost201ResponsePermissions struct {
	// 
	Cephfs []string `json:"cephfs"`
}

type _ApiAuthCheckPost201ResponsePermissions ApiAuthCheckPost201ResponsePermissions

// NewApiAuthCheckPost201ResponsePermissions instantiates a new ApiAuthCheckPost201ResponsePermissions object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiAuthCheckPost201ResponsePermissions(cephfs []string) *ApiAuthCheckPost201ResponsePermissions {
	this := ApiAuthCheckPost201ResponsePermissions{}
	this.Cephfs = cephfs
	return &this
}

// NewApiAuthCheckPost201ResponsePermissionsWithDefaults instantiates a new ApiAuthCheckPost201ResponsePermissions object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiAuthCheckPost201ResponsePermissionsWithDefaults() *ApiAuthCheckPost201ResponsePermissions {
	this := ApiAuthCheckPost201ResponsePermissions{}
	return &this
}

// GetCephfs returns the Cephfs field value
func (o *ApiAuthCheckPost201ResponsePermissions) GetCephfs() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Cephfs
}

// GetCephfsOk returns a tuple with the Cephfs field value
// and a boolean to check if the value has been set.
func (o *ApiAuthCheckPost201ResponsePermissions) GetCephfsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Cephfs, true
}

// SetCephfs sets field value
func (o *ApiAuthCheckPost201ResponsePermissions) SetCephfs(v []string) {
	o.Cephfs = v
}

func (o ApiAuthCheckPost201ResponsePermissions) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiAuthCheckPost201ResponsePermissions) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["cephfs"] = o.Cephfs
	return toSerialize, nil
}

func (o *ApiAuthCheckPost201ResponsePermissions) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"cephfs",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiAuthCheckPost201ResponsePermissions := _ApiAuthCheckPost201ResponsePermissions{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiAuthCheckPost201ResponsePermissions)

	if err != nil {
		return err
	}

	*o = ApiAuthCheckPost201ResponsePermissions(varApiAuthCheckPost201ResponsePermissions)

	return err
}

type NullableApiAuthCheckPost201ResponsePermissions struct {
	value *ApiAuthCheckPost201ResponsePermissions
	isSet bool
}

func (v NullableApiAuthCheckPost201ResponsePermissions) Get() *ApiAuthCheckPost201ResponsePermissions {
	return v.value
}

func (v *NullableApiAuthCheckPost201ResponsePermissions) Set(val *ApiAuthCheckPost201ResponsePermissions) {
	v.value = val
	v.isSet = true
}

func (v NullableApiAuthCheckPost201ResponsePermissions) IsSet() bool {
	return v.isSet
}

func (v *NullableApiAuthCheckPost201ResponsePermissions) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiAuthCheckPost201ResponsePermissions(val *ApiAuthCheckPost201ResponsePermissions) *NullableApiAuthCheckPost201ResponsePermissions {
	return &NullableApiAuthCheckPost201ResponsePermissions{value: val, isSet: true}
}

func (v NullableApiAuthCheckPost201ResponsePermissions) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiAuthCheckPost201ResponsePermissions) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


