/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
)

// checks if the ApiClusterConfFilterGet200ResponseInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiClusterConfFilterGet200ResponseInner{}

// ApiClusterConfFilterGet200ResponseInner struct for ApiClusterConfFilterGet200ResponseInner
type ApiClusterConfFilterGet200ResponseInner struct {
	// Check if can update at runtime
	CanUpdateAtRuntime *bool `json:"can_update_at_runtime,omitempty"`
	// Daemon specific default value
	DaemonDefault *string `json:"daemon_default,omitempty"`
	// Default value for the config option
	Default *string `json:"default,omitempty"`
	// Description of the configuration
	Desc *string `json:"desc,omitempty"`
	// List of enums allowed
	EnumValues []string `json:"enum_values,omitempty"`
	// List of flags associated
	Flags []string `json:"flags,omitempty"`
	// Config option level
	Level *string `json:"level,omitempty"`
	// Elaborated description
	LongDesc *string `json:"long_desc,omitempty"`
	// Maximum value
	Max *string `json:"max,omitempty"`
	// Minimum value
	Min *string `json:"min,omitempty"`
	// Name of the config option
	Name *string `json:"name,omitempty"`
	// Related config options
	SeeAlso []string `json:"see_also,omitempty"`
	// Services associated with the config option
	Services []string `json:"services,omitempty"`
	// Tags associated with the cluster
	Tags []string `json:"tags,omitempty"`
	// Config option type
	Type *string `json:"type,omitempty"`
}

// NewApiClusterConfFilterGet200ResponseInner instantiates a new ApiClusterConfFilterGet200ResponseInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClusterConfFilterGet200ResponseInner() *ApiClusterConfFilterGet200ResponseInner {
	this := ApiClusterConfFilterGet200ResponseInner{}
	return &this
}

// NewApiClusterConfFilterGet200ResponseInnerWithDefaults instantiates a new ApiClusterConfFilterGet200ResponseInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClusterConfFilterGet200ResponseInnerWithDefaults() *ApiClusterConfFilterGet200ResponseInner {
	this := ApiClusterConfFilterGet200ResponseInner{}
	return &this
}

// GetCanUpdateAtRuntime returns the CanUpdateAtRuntime field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetCanUpdateAtRuntime() bool {
	if o == nil || IsNil(o.CanUpdateAtRuntime) {
		var ret bool
		return ret
	}
	return *o.CanUpdateAtRuntime
}

// GetCanUpdateAtRuntimeOk returns a tuple with the CanUpdateAtRuntime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetCanUpdateAtRuntimeOk() (*bool, bool) {
	if o == nil || IsNil(o.CanUpdateAtRuntime) {
		return nil, false
	}
	return o.CanUpdateAtRuntime, true
}

// HasCanUpdateAtRuntime returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasCanUpdateAtRuntime() bool {
	if o != nil && !IsNil(o.CanUpdateAtRuntime) {
		return true
	}

	return false
}

// SetCanUpdateAtRuntime gets a reference to the given bool and assigns it to the CanUpdateAtRuntime field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetCanUpdateAtRuntime(v bool) {
	o.CanUpdateAtRuntime = &v
}

// GetDaemonDefault returns the DaemonDefault field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDaemonDefault() string {
	if o == nil || IsNil(o.DaemonDefault) {
		var ret string
		return ret
	}
	return *o.DaemonDefault
}

// GetDaemonDefaultOk returns a tuple with the DaemonDefault field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDaemonDefaultOk() (*string, bool) {
	if o == nil || IsNil(o.DaemonDefault) {
		return nil, false
	}
	return o.DaemonDefault, true
}

// HasDaemonDefault returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasDaemonDefault() bool {
	if o != nil && !IsNil(o.DaemonDefault) {
		return true
	}

	return false
}

// SetDaemonDefault gets a reference to the given string and assigns it to the DaemonDefault field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetDaemonDefault(v string) {
	o.DaemonDefault = &v
}

// GetDefault returns the Default field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDefault() string {
	if o == nil || IsNil(o.Default) {
		var ret string
		return ret
	}
	return *o.Default
}

// GetDefaultOk returns a tuple with the Default field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDefaultOk() (*string, bool) {
	if o == nil || IsNil(o.Default) {
		return nil, false
	}
	return o.Default, true
}

// HasDefault returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasDefault() bool {
	if o != nil && !IsNil(o.Default) {
		return true
	}

	return false
}

// SetDefault gets a reference to the given string and assigns it to the Default field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetDefault(v string) {
	o.Default = &v
}

// GetDesc returns the Desc field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDesc() string {
	if o == nil || IsNil(o.Desc) {
		var ret string
		return ret
	}
	return *o.Desc
}

// GetDescOk returns a tuple with the Desc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetDescOk() (*string, bool) {
	if o == nil || IsNil(o.Desc) {
		return nil, false
	}
	return o.Desc, true
}

// HasDesc returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasDesc() bool {
	if o != nil && !IsNil(o.Desc) {
		return true
	}

	return false
}

// SetDesc gets a reference to the given string and assigns it to the Desc field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetDesc(v string) {
	o.Desc = &v
}

// GetEnumValues returns the EnumValues field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetEnumValues() []string {
	if o == nil || IsNil(o.EnumValues) {
		var ret []string
		return ret
	}
	return o.EnumValues
}

// GetEnumValuesOk returns a tuple with the EnumValues field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetEnumValuesOk() ([]string, bool) {
	if o == nil || IsNil(o.EnumValues) {
		return nil, false
	}
	return o.EnumValues, true
}

// HasEnumValues returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasEnumValues() bool {
	if o != nil && !IsNil(o.EnumValues) {
		return true
	}

	return false
}

// SetEnumValues gets a reference to the given []string and assigns it to the EnumValues field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetEnumValues(v []string) {
	o.EnumValues = v
}

// GetFlags returns the Flags field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetFlags() []string {
	if o == nil || IsNil(o.Flags) {
		var ret []string
		return ret
	}
	return o.Flags
}

// GetFlagsOk returns a tuple with the Flags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetFlagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Flags) {
		return nil, false
	}
	return o.Flags, true
}

// HasFlags returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasFlags() bool {
	if o != nil && !IsNil(o.Flags) {
		return true
	}

	return false
}

// SetFlags gets a reference to the given []string and assigns it to the Flags field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetFlags(v []string) {
	o.Flags = v
}

// GetLevel returns the Level field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetLevel() string {
	if o == nil || IsNil(o.Level) {
		var ret string
		return ret
	}
	return *o.Level
}

// GetLevelOk returns a tuple with the Level field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetLevelOk() (*string, bool) {
	if o == nil || IsNil(o.Level) {
		return nil, false
	}
	return o.Level, true
}

// HasLevel returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasLevel() bool {
	if o != nil && !IsNil(o.Level) {
		return true
	}

	return false
}

// SetLevel gets a reference to the given string and assigns it to the Level field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetLevel(v string) {
	o.Level = &v
}

// GetLongDesc returns the LongDesc field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetLongDesc() string {
	if o == nil || IsNil(o.LongDesc) {
		var ret string
		return ret
	}
	return *o.LongDesc
}

// GetLongDescOk returns a tuple with the LongDesc field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetLongDescOk() (*string, bool) {
	if o == nil || IsNil(o.LongDesc) {
		return nil, false
	}
	return o.LongDesc, true
}

// HasLongDesc returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasLongDesc() bool {
	if o != nil && !IsNil(o.LongDesc) {
		return true
	}

	return false
}

// SetLongDesc gets a reference to the given string and assigns it to the LongDesc field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetLongDesc(v string) {
	o.LongDesc = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetMax() string {
	if o == nil || IsNil(o.Max) {
		var ret string
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetMaxOk() (*string, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given string and assigns it to the Max field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetMax(v string) {
	o.Max = &v
}

// GetMin returns the Min field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetMin() string {
	if o == nil || IsNil(o.Min) {
		var ret string
		return ret
	}
	return *o.Min
}

// GetMinOk returns a tuple with the Min field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetMinOk() (*string, bool) {
	if o == nil || IsNil(o.Min) {
		return nil, false
	}
	return o.Min, true
}

// HasMin returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasMin() bool {
	if o != nil && !IsNil(o.Min) {
		return true
	}

	return false
}

// SetMin gets a reference to the given string and assigns it to the Min field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetMin(v string) {
	o.Min = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetName(v string) {
	o.Name = &v
}

// GetSeeAlso returns the SeeAlso field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetSeeAlso() []string {
	if o == nil || IsNil(o.SeeAlso) {
		var ret []string
		return ret
	}
	return o.SeeAlso
}

// GetSeeAlsoOk returns a tuple with the SeeAlso field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetSeeAlsoOk() ([]string, bool) {
	if o == nil || IsNil(o.SeeAlso) {
		return nil, false
	}
	return o.SeeAlso, true
}

// HasSeeAlso returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasSeeAlso() bool {
	if o != nil && !IsNil(o.SeeAlso) {
		return true
	}

	return false
}

// SetSeeAlso gets a reference to the given []string and assigns it to the SeeAlso field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetSeeAlso(v []string) {
	o.SeeAlso = v
}

// GetServices returns the Services field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetServices() []string {
	if o == nil || IsNil(o.Services) {
		var ret []string
		return ret
	}
	return o.Services
}

// GetServicesOk returns a tuple with the Services field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetServicesOk() ([]string, bool) {
	if o == nil || IsNil(o.Services) {
		return nil, false
	}
	return o.Services, true
}

// HasServices returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasServices() bool {
	if o != nil && !IsNil(o.Services) {
		return true
	}

	return false
}

// SetServices gets a reference to the given []string and assigns it to the Services field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetServices(v []string) {
	o.Services = v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetTags(v []string) {
	o.Tags = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiClusterConfFilterGet200ResponseInner) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiClusterConfFilterGet200ResponseInner) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiClusterConfFilterGet200ResponseInner) SetType(v string) {
	o.Type = &v
}

func (o ApiClusterConfFilterGet200ResponseInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiClusterConfFilterGet200ResponseInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CanUpdateAtRuntime) {
		toSerialize["can_update_at_runtime"] = o.CanUpdateAtRuntime
	}
	if !IsNil(o.DaemonDefault) {
		toSerialize["daemon_default"] = o.DaemonDefault
	}
	if !IsNil(o.Default) {
		toSerialize["default"] = o.Default
	}
	if !IsNil(o.Desc) {
		toSerialize["desc"] = o.Desc
	}
	if !IsNil(o.EnumValues) {
		toSerialize["enum_values"] = o.EnumValues
	}
	if !IsNil(o.Flags) {
		toSerialize["flags"] = o.Flags
	}
	if !IsNil(o.Level) {
		toSerialize["level"] = o.Level
	}
	if !IsNil(o.LongDesc) {
		toSerialize["long_desc"] = o.LongDesc
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Min) {
		toSerialize["min"] = o.Min
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.SeeAlso) {
		toSerialize["see_also"] = o.SeeAlso
	}
	if !IsNil(o.Services) {
		toSerialize["services"] = o.Services
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableApiClusterConfFilterGet200ResponseInner struct {
	value *ApiClusterConfFilterGet200ResponseInner
	isSet bool
}

func (v NullableApiClusterConfFilterGet200ResponseInner) Get() *ApiClusterConfFilterGet200ResponseInner {
	return v.value
}

func (v *NullableApiClusterConfFilterGet200ResponseInner) Set(val *ApiClusterConfFilterGet200ResponseInner) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClusterConfFilterGet200ResponseInner) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClusterConfFilterGet200ResponseInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClusterConfFilterGet200ResponseInner(val *ApiClusterConfFilterGet200ResponseInner) *NullableApiClusterConfFilterGet200ResponseInner {
	return &NullableApiClusterConfFilterGet200ResponseInner{value: val, isSet: true}
}

func (v NullableApiClusterConfFilterGet200ResponseInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClusterConfFilterGet200ResponseInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


