/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiTelemetryReportGet200ResponseReportMetadataMonCpu type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTelemetryReportGet200ResponseReportMetadataMonCpu{}

// ApiTelemetryReportGet200ResponseReportMetadataMonCpu 
type ApiTelemetryReportGet200ResponseReportMetadataMonCpu struct {
	// 
	IntelRCoreTMI78665UCPU190GHz int32 `json:"Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz"`
}

type _ApiTelemetryReportGet200ResponseReportMetadataMonCpu ApiTelemetryReportGet200ResponseReportMetadataMonCpu

// NewApiTelemetryReportGet200ResponseReportMetadataMonCpu instantiates a new ApiTelemetryReportGet200ResponseReportMetadataMonCpu object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTelemetryReportGet200ResponseReportMetadataMonCpu(intelRCoreTMI78665UCPU190GHz int32) *ApiTelemetryReportGet200ResponseReportMetadataMonCpu {
	this := ApiTelemetryReportGet200ResponseReportMetadataMonCpu{}
	this.IntelRCoreTMI78665UCPU190GHz = intelRCoreTMI78665UCPU190GHz
	return &this
}

// NewApiTelemetryReportGet200ResponseReportMetadataMonCpuWithDefaults instantiates a new ApiTelemetryReportGet200ResponseReportMetadataMonCpu object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTelemetryReportGet200ResponseReportMetadataMonCpuWithDefaults() *ApiTelemetryReportGet200ResponseReportMetadataMonCpu {
	this := ApiTelemetryReportGet200ResponseReportMetadataMonCpu{}
	return &this
}

// GetIntelRCoreTMI78665UCPU190GHz returns the IntelRCoreTMI78665UCPU190GHz field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) GetIntelRCoreTMI78665UCPU190GHz() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.IntelRCoreTMI78665UCPU190GHz
}

// GetIntelRCoreTMI78665UCPU190GHzOk returns a tuple with the IntelRCoreTMI78665UCPU190GHz field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) GetIntelRCoreTMI78665UCPU190GHzOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.IntelRCoreTMI78665UCPU190GHz, true
}

// SetIntelRCoreTMI78665UCPU190GHz sets field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) SetIntelRCoreTMI78665UCPU190GHz(v int32) {
	o.IntelRCoreTMI78665UCPU190GHz = v
}

func (o ApiTelemetryReportGet200ResponseReportMetadataMonCpu) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTelemetryReportGet200ResponseReportMetadataMonCpu) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz"] = o.IntelRCoreTMI78665UCPU190GHz
	return toSerialize, nil
}

func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTelemetryReportGet200ResponseReportMetadataMonCpu := _ApiTelemetryReportGet200ResponseReportMetadataMonCpu{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTelemetryReportGet200ResponseReportMetadataMonCpu)

	if err != nil {
		return err
	}

	*o = ApiTelemetryReportGet200ResponseReportMetadataMonCpu(varApiTelemetryReportGet200ResponseReportMetadataMonCpu)

	return err
}

type NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu struct {
	value *ApiTelemetryReportGet200ResponseReportMetadataMonCpu
	isSet bool
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) Get() *ApiTelemetryReportGet200ResponseReportMetadataMonCpu {
	return v.value
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) Set(val *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTelemetryReportGet200ResponseReportMetadataMonCpu(val *ApiTelemetryReportGet200ResponseReportMetadataMonCpu) *NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu {
	return &NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu{value: val, isSet: true}
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCpu) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


