/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiNvmeofSubsystemNqnListenerPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiNvmeofSubsystemNqnListenerPostRequest{}

// ApiNvmeofSubsystemNqnListenerPostRequest struct for ApiNvmeofSubsystemNqnListenerPostRequest
type ApiNvmeofSubsystemNqnListenerPostRequest struct {
	// NVMeoF address family (0 - IPv4, 1 - IPv6)
	Adrfam *int32 `json:"adrfam,omitempty"`
	// NVMeoF gateway group
	GwGroup *string `json:"gw_group,omitempty"`
	// NVMeoF hostname
	HostName string `json:"host_name"`
	// NVMeoF transport address
	Traddr string `json:"traddr"`
	// NVMeoF transport service port
	Trsvcid *int32 `json:"trsvcid,omitempty"`
}

type _ApiNvmeofSubsystemNqnListenerPostRequest ApiNvmeofSubsystemNqnListenerPostRequest

// NewApiNvmeofSubsystemNqnListenerPostRequest instantiates a new ApiNvmeofSubsystemNqnListenerPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiNvmeofSubsystemNqnListenerPostRequest(hostName string, traddr string) *ApiNvmeofSubsystemNqnListenerPostRequest {
	this := ApiNvmeofSubsystemNqnListenerPostRequest{}
	var adrfam int32 = 0
	this.Adrfam = &adrfam
	this.HostName = hostName
	this.Traddr = traddr
	var trsvcid int32 = 4420
	this.Trsvcid = &trsvcid
	return &this
}

// NewApiNvmeofSubsystemNqnListenerPostRequestWithDefaults instantiates a new ApiNvmeofSubsystemNqnListenerPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiNvmeofSubsystemNqnListenerPostRequestWithDefaults() *ApiNvmeofSubsystemNqnListenerPostRequest {
	this := ApiNvmeofSubsystemNqnListenerPostRequest{}
	var adrfam int32 = 0
	this.Adrfam = &adrfam
	var trsvcid int32 = 4420
	this.Trsvcid = &trsvcid
	return &this
}

// GetAdrfam returns the Adrfam field value if set, zero value otherwise.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetAdrfam() int32 {
	if o == nil || IsNil(o.Adrfam) {
		var ret int32
		return ret
	}
	return *o.Adrfam
}

// GetAdrfamOk returns a tuple with the Adrfam field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetAdrfamOk() (*int32, bool) {
	if o == nil || IsNil(o.Adrfam) {
		return nil, false
	}
	return o.Adrfam, true
}

// HasAdrfam returns a boolean if a field has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) HasAdrfam() bool {
	if o != nil && !IsNil(o.Adrfam) {
		return true
	}

	return false
}

// SetAdrfam gets a reference to the given int32 and assigns it to the Adrfam field.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) SetAdrfam(v int32) {
	o.Adrfam = &v
}

// GetGwGroup returns the GwGroup field value if set, zero value otherwise.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetGwGroup() string {
	if o == nil || IsNil(o.GwGroup) {
		var ret string
		return ret
	}
	return *o.GwGroup
}

// GetGwGroupOk returns a tuple with the GwGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetGwGroupOk() (*string, bool) {
	if o == nil || IsNil(o.GwGroup) {
		return nil, false
	}
	return o.GwGroup, true
}

// HasGwGroup returns a boolean if a field has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) HasGwGroup() bool {
	if o != nil && !IsNil(o.GwGroup) {
		return true
	}

	return false
}

// SetGwGroup gets a reference to the given string and assigns it to the GwGroup field.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) SetGwGroup(v string) {
	o.GwGroup = &v
}

// GetHostName returns the HostName field value
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetHostName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.HostName
}

// GetHostNameOk returns a tuple with the HostName field value
// and a boolean to check if the value has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetHostNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.HostName, true
}

// SetHostName sets field value
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) SetHostName(v string) {
	o.HostName = v
}

// GetTraddr returns the Traddr field value
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetTraddr() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Traddr
}

// GetTraddrOk returns a tuple with the Traddr field value
// and a boolean to check if the value has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetTraddrOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Traddr, true
}

// SetTraddr sets field value
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) SetTraddr(v string) {
	o.Traddr = v
}

// GetTrsvcid returns the Trsvcid field value if set, zero value otherwise.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetTrsvcid() int32 {
	if o == nil || IsNil(o.Trsvcid) {
		var ret int32
		return ret
	}
	return *o.Trsvcid
}

// GetTrsvcidOk returns a tuple with the Trsvcid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) GetTrsvcidOk() (*int32, bool) {
	if o == nil || IsNil(o.Trsvcid) {
		return nil, false
	}
	return o.Trsvcid, true
}

// HasTrsvcid returns a boolean if a field has been set.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) HasTrsvcid() bool {
	if o != nil && !IsNil(o.Trsvcid) {
		return true
	}

	return false
}

// SetTrsvcid gets a reference to the given int32 and assigns it to the Trsvcid field.
func (o *ApiNvmeofSubsystemNqnListenerPostRequest) SetTrsvcid(v int32) {
	o.Trsvcid = &v
}

func (o ApiNvmeofSubsystemNqnListenerPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiNvmeofSubsystemNqnListenerPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Adrfam) {
		toSerialize["adrfam"] = o.Adrfam
	}
	if !IsNil(o.GwGroup) {
		toSerialize["gw_group"] = o.GwGroup
	}
	toSerialize["host_name"] = o.HostName
	toSerialize["traddr"] = o.Traddr
	if !IsNil(o.Trsvcid) {
		toSerialize["trsvcid"] = o.Trsvcid
	}
	return toSerialize, nil
}

func (o *ApiNvmeofSubsystemNqnListenerPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"host_name",
		"traddr",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiNvmeofSubsystemNqnListenerPostRequest := _ApiNvmeofSubsystemNqnListenerPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiNvmeofSubsystemNqnListenerPostRequest)

	if err != nil {
		return err
	}

	*o = ApiNvmeofSubsystemNqnListenerPostRequest(varApiNvmeofSubsystemNqnListenerPostRequest)

	return err
}

type NullableApiNvmeofSubsystemNqnListenerPostRequest struct {
	value *ApiNvmeofSubsystemNqnListenerPostRequest
	isSet bool
}

func (v NullableApiNvmeofSubsystemNqnListenerPostRequest) Get() *ApiNvmeofSubsystemNqnListenerPostRequest {
	return v.value
}

func (v *NullableApiNvmeofSubsystemNqnListenerPostRequest) Set(val *ApiNvmeofSubsystemNqnListenerPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiNvmeofSubsystemNqnListenerPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiNvmeofSubsystemNqnListenerPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiNvmeofSubsystemNqnListenerPostRequest(val *ApiNvmeofSubsystemNqnListenerPostRequest) *NullableApiNvmeofSubsystemNqnListenerPostRequest {
	return &NullableApiNvmeofSubsystemNqnListenerPostRequest{value: val, isSet: true}
}

func (v NullableApiNvmeofSubsystemNqnListenerPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiNvmeofSubsystemNqnListenerPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


