/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiBlockImageImageSpecCopyPostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiBlockImageImageSpecCopyPostRequest{}

// ApiBlockImageImageSpecCopyPostRequest struct for ApiBlockImageImageSpecCopyPostRequest
type ApiBlockImageImageSpecCopyPostRequest struct {
	Configuration *string `json:"configuration,omitempty"`
	DataPool *string `json:"data_pool,omitempty"`
	DestImageName string `json:"dest_image_name"`
	DestNamespace string `json:"dest_namespace"`
	DestPoolName string `json:"dest_pool_name"`
	Features *string `json:"features,omitempty"`
	Metadata *string `json:"metadata,omitempty"`
	ObjSize *int32 `json:"obj_size,omitempty"`
	SnapshotName *string `json:"snapshot_name,omitempty"`
	StripeCount *int32 `json:"stripe_count,omitempty"`
	StripeUnit *string `json:"stripe_unit,omitempty"`
}

type _ApiBlockImageImageSpecCopyPostRequest ApiBlockImageImageSpecCopyPostRequest

// NewApiBlockImageImageSpecCopyPostRequest instantiates a new ApiBlockImageImageSpecCopyPostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBlockImageImageSpecCopyPostRequest(destImageName string, destNamespace string, destPoolName string) *ApiBlockImageImageSpecCopyPostRequest {
	this := ApiBlockImageImageSpecCopyPostRequest{}
	this.DestImageName = destImageName
	this.DestNamespace = destNamespace
	this.DestPoolName = destPoolName
	return &this
}

// NewApiBlockImageImageSpecCopyPostRequestWithDefaults instantiates a new ApiBlockImageImageSpecCopyPostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBlockImageImageSpecCopyPostRequestWithDefaults() *ApiBlockImageImageSpecCopyPostRequest {
	this := ApiBlockImageImageSpecCopyPostRequest{}
	return &this
}

// GetConfiguration returns the Configuration field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetConfiguration() string {
	if o == nil || IsNil(o.Configuration) {
		var ret string
		return ret
	}
	return *o.Configuration
}

// GetConfigurationOk returns a tuple with the Configuration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetConfigurationOk() (*string, bool) {
	if o == nil || IsNil(o.Configuration) {
		return nil, false
	}
	return o.Configuration, true
}

// HasConfiguration returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasConfiguration() bool {
	if o != nil && !IsNil(o.Configuration) {
		return true
	}

	return false
}

// SetConfiguration gets a reference to the given string and assigns it to the Configuration field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetConfiguration(v string) {
	o.Configuration = &v
}

// GetDataPool returns the DataPool field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDataPool() string {
	if o == nil || IsNil(o.DataPool) {
		var ret string
		return ret
	}
	return *o.DataPool
}

// GetDataPoolOk returns a tuple with the DataPool field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDataPoolOk() (*string, bool) {
	if o == nil || IsNil(o.DataPool) {
		return nil, false
	}
	return o.DataPool, true
}

// HasDataPool returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasDataPool() bool {
	if o != nil && !IsNil(o.DataPool) {
		return true
	}

	return false
}

// SetDataPool gets a reference to the given string and assigns it to the DataPool field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetDataPool(v string) {
	o.DataPool = &v
}

// GetDestImageName returns the DestImageName field value
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestImageName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestImageName
}

// GetDestImageNameOk returns a tuple with the DestImageName field value
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestImageNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestImageName, true
}

// SetDestImageName sets field value
func (o *ApiBlockImageImageSpecCopyPostRequest) SetDestImageName(v string) {
	o.DestImageName = v
}

// GetDestNamespace returns the DestNamespace field value
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestNamespace() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestNamespace
}

// GetDestNamespaceOk returns a tuple with the DestNamespace field value
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestNamespaceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestNamespace, true
}

// SetDestNamespace sets field value
func (o *ApiBlockImageImageSpecCopyPostRequest) SetDestNamespace(v string) {
	o.DestNamespace = v
}

// GetDestPoolName returns the DestPoolName field value
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestPoolName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DestPoolName
}

// GetDestPoolNameOk returns a tuple with the DestPoolName field value
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetDestPoolNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DestPoolName, true
}

// SetDestPoolName sets field value
func (o *ApiBlockImageImageSpecCopyPostRequest) SetDestPoolName(v string) {
	o.DestPoolName = v
}

// GetFeatures returns the Features field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetFeatures() string {
	if o == nil || IsNil(o.Features) {
		var ret string
		return ret
	}
	return *o.Features
}

// GetFeaturesOk returns a tuple with the Features field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetFeaturesOk() (*string, bool) {
	if o == nil || IsNil(o.Features) {
		return nil, false
	}
	return o.Features, true
}

// HasFeatures returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasFeatures() bool {
	if o != nil && !IsNil(o.Features) {
		return true
	}

	return false
}

// SetFeatures gets a reference to the given string and assigns it to the Features field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetFeatures(v string) {
	o.Features = &v
}

// GetMetadata returns the Metadata field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetMetadata() string {
	if o == nil || IsNil(o.Metadata) {
		var ret string
		return ret
	}
	return *o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetMetadataOk() (*string, bool) {
	if o == nil || IsNil(o.Metadata) {
		return nil, false
	}
	return o.Metadata, true
}

// HasMetadata returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasMetadata() bool {
	if o != nil && !IsNil(o.Metadata) {
		return true
	}

	return false
}

// SetMetadata gets a reference to the given string and assigns it to the Metadata field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetMetadata(v string) {
	o.Metadata = &v
}

// GetObjSize returns the ObjSize field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetObjSize() int32 {
	if o == nil || IsNil(o.ObjSize) {
		var ret int32
		return ret
	}
	return *o.ObjSize
}

// GetObjSizeOk returns a tuple with the ObjSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetObjSizeOk() (*int32, bool) {
	if o == nil || IsNil(o.ObjSize) {
		return nil, false
	}
	return o.ObjSize, true
}

// HasObjSize returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasObjSize() bool {
	if o != nil && !IsNil(o.ObjSize) {
		return true
	}

	return false
}

// SetObjSize gets a reference to the given int32 and assigns it to the ObjSize field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetObjSize(v int32) {
	o.ObjSize = &v
}

// GetSnapshotName returns the SnapshotName field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetSnapshotName() string {
	if o == nil || IsNil(o.SnapshotName) {
		var ret string
		return ret
	}
	return *o.SnapshotName
}

// GetSnapshotNameOk returns a tuple with the SnapshotName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetSnapshotNameOk() (*string, bool) {
	if o == nil || IsNil(o.SnapshotName) {
		return nil, false
	}
	return o.SnapshotName, true
}

// HasSnapshotName returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasSnapshotName() bool {
	if o != nil && !IsNil(o.SnapshotName) {
		return true
	}

	return false
}

// SetSnapshotName gets a reference to the given string and assigns it to the SnapshotName field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetSnapshotName(v string) {
	o.SnapshotName = &v
}

// GetStripeCount returns the StripeCount field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetStripeCount() int32 {
	if o == nil || IsNil(o.StripeCount) {
		var ret int32
		return ret
	}
	return *o.StripeCount
}

// GetStripeCountOk returns a tuple with the StripeCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetStripeCountOk() (*int32, bool) {
	if o == nil || IsNil(o.StripeCount) {
		return nil, false
	}
	return o.StripeCount, true
}

// HasStripeCount returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasStripeCount() bool {
	if o != nil && !IsNil(o.StripeCount) {
		return true
	}

	return false
}

// SetStripeCount gets a reference to the given int32 and assigns it to the StripeCount field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetStripeCount(v int32) {
	o.StripeCount = &v
}

// GetStripeUnit returns the StripeUnit field value if set, zero value otherwise.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetStripeUnit() string {
	if o == nil || IsNil(o.StripeUnit) {
		var ret string
		return ret
	}
	return *o.StripeUnit
}

// GetStripeUnitOk returns a tuple with the StripeUnit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) GetStripeUnitOk() (*string, bool) {
	if o == nil || IsNil(o.StripeUnit) {
		return nil, false
	}
	return o.StripeUnit, true
}

// HasStripeUnit returns a boolean if a field has been set.
func (o *ApiBlockImageImageSpecCopyPostRequest) HasStripeUnit() bool {
	if o != nil && !IsNil(o.StripeUnit) {
		return true
	}

	return false
}

// SetStripeUnit gets a reference to the given string and assigns it to the StripeUnit field.
func (o *ApiBlockImageImageSpecCopyPostRequest) SetStripeUnit(v string) {
	o.StripeUnit = &v
}

func (o ApiBlockImageImageSpecCopyPostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiBlockImageImageSpecCopyPostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configuration) {
		toSerialize["configuration"] = o.Configuration
	}
	if !IsNil(o.DataPool) {
		toSerialize["data_pool"] = o.DataPool
	}
	toSerialize["dest_image_name"] = o.DestImageName
	toSerialize["dest_namespace"] = o.DestNamespace
	toSerialize["dest_pool_name"] = o.DestPoolName
	if !IsNil(o.Features) {
		toSerialize["features"] = o.Features
	}
	if !IsNil(o.Metadata) {
		toSerialize["metadata"] = o.Metadata
	}
	if !IsNil(o.ObjSize) {
		toSerialize["obj_size"] = o.ObjSize
	}
	if !IsNil(o.SnapshotName) {
		toSerialize["snapshot_name"] = o.SnapshotName
	}
	if !IsNil(o.StripeCount) {
		toSerialize["stripe_count"] = o.StripeCount
	}
	if !IsNil(o.StripeUnit) {
		toSerialize["stripe_unit"] = o.StripeUnit
	}
	return toSerialize, nil
}

func (o *ApiBlockImageImageSpecCopyPostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"dest_image_name",
		"dest_namespace",
		"dest_pool_name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiBlockImageImageSpecCopyPostRequest := _ApiBlockImageImageSpecCopyPostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiBlockImageImageSpecCopyPostRequest)

	if err != nil {
		return err
	}

	*o = ApiBlockImageImageSpecCopyPostRequest(varApiBlockImageImageSpecCopyPostRequest)

	return err
}

type NullableApiBlockImageImageSpecCopyPostRequest struct {
	value *ApiBlockImageImageSpecCopyPostRequest
	isSet bool
}

func (v NullableApiBlockImageImageSpecCopyPostRequest) Get() *ApiBlockImageImageSpecCopyPostRequest {
	return v.value
}

func (v *NullableApiBlockImageImageSpecCopyPostRequest) Set(val *ApiBlockImageImageSpecCopyPostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBlockImageImageSpecCopyPostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBlockImageImageSpecCopyPostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBlockImageImageSpecCopyPostRequest(val *ApiBlockImageImageSpecCopyPostRequest) *NullableApiBlockImageImageSpecCopyPostRequest {
	return &NullableApiBlockImageImageSpecCopyPostRequest{value: val, isSet: true}
}

func (v NullableApiBlockImageImageSpecCopyPostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBlockImageImageSpecCopyPostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


