/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiMonitorGet200ResponseMonStatusFeatureMap type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiMonitorGet200ResponseMonStatusFeatureMap{}

// ApiMonitorGet200ResponseMonStatusFeatureMap 
type ApiMonitorGet200ResponseMonStatusFeatureMap struct {
	// 
	Client []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner `json:"client"`
	// 
	Mds []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner `json:"mds"`
	// 
	Mgr []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner `json:"mgr"`
	// 
	Mon []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner `json:"mon"`
}

type _ApiMonitorGet200ResponseMonStatusFeatureMap ApiMonitorGet200ResponseMonStatusFeatureMap

// NewApiMonitorGet200ResponseMonStatusFeatureMap instantiates a new ApiMonitorGet200ResponseMonStatusFeatureMap object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiMonitorGet200ResponseMonStatusFeatureMap(client []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, mds []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, mgr []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, mon []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner) *ApiMonitorGet200ResponseMonStatusFeatureMap {
	this := ApiMonitorGet200ResponseMonStatusFeatureMap{}
	this.Client = client
	this.Mds = mds
	this.Mgr = mgr
	this.Mon = mon
	return &this
}

// NewApiMonitorGet200ResponseMonStatusFeatureMapWithDefaults instantiates a new ApiMonitorGet200ResponseMonStatusFeatureMap object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiMonitorGet200ResponseMonStatusFeatureMapWithDefaults() *ApiMonitorGet200ResponseMonStatusFeatureMap {
	this := ApiMonitorGet200ResponseMonStatusFeatureMap{}
	return &this
}

// GetClient returns the Client field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetClient() []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner {
	if o == nil {
		var ret []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner
		return ret
	}

	return o.Client
}

// GetClientOk returns a tuple with the Client field value
// and a boolean to check if the value has been set.
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetClientOk() ([]ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Client, true
}

// SetClient sets field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) SetClient(v []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner) {
	o.Client = v
}

// GetMds returns the Mds field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMds() []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner {
	if o == nil {
		var ret []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner
		return ret
	}

	return o.Mds
}

// GetMdsOk returns a tuple with the Mds field value
// and a boolean to check if the value has been set.
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMdsOk() ([]ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mds, true
}

// SetMds sets field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) SetMds(v []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner) {
	o.Mds = v
}

// GetMgr returns the Mgr field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMgr() []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner {
	if o == nil {
		var ret []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner
		return ret
	}

	return o.Mgr
}

// GetMgrOk returns a tuple with the Mgr field value
// and a boolean to check if the value has been set.
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMgrOk() ([]ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mgr, true
}

// SetMgr sets field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) SetMgr(v []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner) {
	o.Mgr = v
}

// GetMon returns the Mon field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMon() []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner {
	if o == nil {
		var ret []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner
		return ret
	}

	return o.Mon
}

// GetMonOk returns a tuple with the Mon field value
// and a boolean to check if the value has been set.
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) GetMonOk() ([]ApiMonitorGet200ResponseMonStatusFeatureMapClientInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mon, true
}

// SetMon sets field value
func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) SetMon(v []ApiMonitorGet200ResponseMonStatusFeatureMapClientInner) {
	o.Mon = v
}

func (o ApiMonitorGet200ResponseMonStatusFeatureMap) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiMonitorGet200ResponseMonStatusFeatureMap) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["client"] = o.Client
	toSerialize["mds"] = o.Mds
	toSerialize["mgr"] = o.Mgr
	toSerialize["mon"] = o.Mon
	return toSerialize, nil
}

func (o *ApiMonitorGet200ResponseMonStatusFeatureMap) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"client",
		"mds",
		"mgr",
		"mon",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiMonitorGet200ResponseMonStatusFeatureMap := _ApiMonitorGet200ResponseMonStatusFeatureMap{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiMonitorGet200ResponseMonStatusFeatureMap)

	if err != nil {
		return err
	}

	*o = ApiMonitorGet200ResponseMonStatusFeatureMap(varApiMonitorGet200ResponseMonStatusFeatureMap)

	return err
}

type NullableApiMonitorGet200ResponseMonStatusFeatureMap struct {
	value *ApiMonitorGet200ResponseMonStatusFeatureMap
	isSet bool
}

func (v NullableApiMonitorGet200ResponseMonStatusFeatureMap) Get() *ApiMonitorGet200ResponseMonStatusFeatureMap {
	return v.value
}

func (v *NullableApiMonitorGet200ResponseMonStatusFeatureMap) Set(val *ApiMonitorGet200ResponseMonStatusFeatureMap) {
	v.value = val
	v.isSet = true
}

func (v NullableApiMonitorGet200ResponseMonStatusFeatureMap) IsSet() bool {
	return v.isSet
}

func (v *NullableApiMonitorGet200ResponseMonStatusFeatureMap) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiMonitorGet200ResponseMonStatusFeatureMap(val *ApiMonitorGet200ResponseMonStatusFeatureMap) *NullableApiMonitorGet200ResponseMonStatusFeatureMap {
	return &NullableApiMonitorGet200ResponseMonStatusFeatureMap{value: val, isSet: true}
}

func (v NullableApiMonitorGet200ResponseMonStatusFeatureMap) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiMonitorGet200ResponseMonStatusFeatureMap) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


