/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiCephfsFsIdTreePostRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCephfsFsIdTreePostRequest{}

// ApiCephfsFsIdTreePostRequest struct for ApiCephfsFsIdTreePostRequest
type ApiCephfsFsIdTreePostRequest struct {
	Path string `json:"path"`
}

type _ApiCephfsFsIdTreePostRequest ApiCephfsFsIdTreePostRequest

// NewApiCephfsFsIdTreePostRequest instantiates a new ApiCephfsFsIdTreePostRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCephfsFsIdTreePostRequest(path string) *ApiCephfsFsIdTreePostRequest {
	this := ApiCephfsFsIdTreePostRequest{}
	this.Path = path
	return &this
}

// NewApiCephfsFsIdTreePostRequestWithDefaults instantiates a new ApiCephfsFsIdTreePostRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCephfsFsIdTreePostRequestWithDefaults() *ApiCephfsFsIdTreePostRequest {
	this := ApiCephfsFsIdTreePostRequest{}
	return &this
}

// GetPath returns the Path field value
func (o *ApiCephfsFsIdTreePostRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ApiCephfsFsIdTreePostRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ApiCephfsFsIdTreePostRequest) SetPath(v string) {
	o.Path = v
}

func (o ApiCephfsFsIdTreePostRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCephfsFsIdTreePostRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *ApiCephfsFsIdTreePostRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCephfsFsIdTreePostRequest := _ApiCephfsFsIdTreePostRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiCephfsFsIdTreePostRequest)

	if err != nil {
		return err
	}

	*o = ApiCephfsFsIdTreePostRequest(varApiCephfsFsIdTreePostRequest)

	return err
}

type NullableApiCephfsFsIdTreePostRequest struct {
	value *ApiCephfsFsIdTreePostRequest
	isSet bool
}

func (v NullableApiCephfsFsIdTreePostRequest) Get() *ApiCephfsFsIdTreePostRequest {
	return v.value
}

func (v *NullableApiCephfsFsIdTreePostRequest) Set(val *ApiCephfsFsIdTreePostRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCephfsFsIdTreePostRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCephfsFsIdTreePostRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCephfsFsIdTreePostRequest(val *ApiCephfsFsIdTreePostRequest) *NullableApiCephfsFsIdTreePostRequest {
	return &NullableApiCephfsFsIdTreePostRequest{value: val, isSet: true}
}

func (v NullableApiCephfsFsIdTreePostRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCephfsFsIdTreePostRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


