/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiClusterPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiClusterPutRequest{}

// ApiClusterPutRequest struct for ApiClusterPutRequest
type ApiClusterPutRequest struct {
	// Cluster Status
	Status string `json:"status"`
}

type _ApiClusterPutRequest ApiClusterPutRequest

// NewApiClusterPutRequest instantiates a new ApiClusterPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiClusterPutRequest(status string) *ApiClusterPutRequest {
	this := ApiClusterPutRequest{}
	this.Status = status
	return &this
}

// NewApiClusterPutRequestWithDefaults instantiates a new ApiClusterPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiClusterPutRequestWithDefaults() *ApiClusterPutRequest {
	this := ApiClusterPutRequest{}
	return &this
}

// GetStatus returns the Status field value
func (o *ApiClusterPutRequest) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *ApiClusterPutRequest) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *ApiClusterPutRequest) SetStatus(v string) {
	o.Status = v
}

func (o ApiClusterPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiClusterPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["status"] = o.Status
	return toSerialize, nil
}

func (o *ApiClusterPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiClusterPutRequest := _ApiClusterPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiClusterPutRequest)

	if err != nil {
		return err
	}

	*o = ApiClusterPutRequest(varApiClusterPutRequest)

	return err
}

type NullableApiClusterPutRequest struct {
	value *ApiClusterPutRequest
	isSet bool
}

func (v NullableApiClusterPutRequest) Get() *ApiClusterPutRequest {
	return v.value
}

func (v *NullableApiClusterPutRequest) Set(val *ApiClusterPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiClusterPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiClusterPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiClusterPutRequest(val *ApiClusterPutRequest) *NullableApiClusterPutRequest {
	return &NullableApiClusterPutRequest{value: val, isSet: true}
}

func (v NullableApiClusterPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiClusterPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


