/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiTelemetryReportGet200ResponseReportMon type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTelemetryReportGet200ResponseReportMon{}

// ApiTelemetryReportGet200ResponseReportMon 
type ApiTelemetryReportGet200ResponseReportMon struct {
	// 
	Count int32 `json:"count"`
	Features ApiTelemetryReportGet200ResponseReportMonFeatures `json:"features"`
	// 
	Ipv4AddrMons int32 `json:"ipv4_addr_mons"`
	// 
	Ipv6AddrMons int32 `json:"ipv6_addr_mons"`
	// 
	MinMonRelease int32 `json:"min_mon_release"`
	// 
	V1AddrMons int32 `json:"v1_addr_mons"`
	// 
	V2AddrMons int32 `json:"v2_addr_mons"`
}

type _ApiTelemetryReportGet200ResponseReportMon ApiTelemetryReportGet200ResponseReportMon

// NewApiTelemetryReportGet200ResponseReportMon instantiates a new ApiTelemetryReportGet200ResponseReportMon object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTelemetryReportGet200ResponseReportMon(count int32, features ApiTelemetryReportGet200ResponseReportMonFeatures, ipv4AddrMons int32, ipv6AddrMons int32, minMonRelease int32, v1AddrMons int32, v2AddrMons int32) *ApiTelemetryReportGet200ResponseReportMon {
	this := ApiTelemetryReportGet200ResponseReportMon{}
	this.Count = count
	this.Features = features
	this.Ipv4AddrMons = ipv4AddrMons
	this.Ipv6AddrMons = ipv6AddrMons
	this.MinMonRelease = minMonRelease
	this.V1AddrMons = v1AddrMons
	this.V2AddrMons = v2AddrMons
	return &this
}

// NewApiTelemetryReportGet200ResponseReportMonWithDefaults instantiates a new ApiTelemetryReportGet200ResponseReportMon object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTelemetryReportGet200ResponseReportMonWithDefaults() *ApiTelemetryReportGet200ResponseReportMon {
	this := ApiTelemetryReportGet200ResponseReportMon{}
	return &this
}

// GetCount returns the Count field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetCount() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Count
}

// GetCountOk returns a tuple with the Count field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetCountOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Count, true
}

// SetCount sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetCount(v int32) {
	o.Count = v
}

// GetFeatures returns the Features field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetFeatures() ApiTelemetryReportGet200ResponseReportMonFeatures {
	if o == nil {
		var ret ApiTelemetryReportGet200ResponseReportMonFeatures
		return ret
	}

	return o.Features
}

// GetFeaturesOk returns a tuple with the Features field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetFeaturesOk() (*ApiTelemetryReportGet200ResponseReportMonFeatures, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Features, true
}

// SetFeatures sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetFeatures(v ApiTelemetryReportGet200ResponseReportMonFeatures) {
	o.Features = v
}

// GetIpv4AddrMons returns the Ipv4AddrMons field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetIpv4AddrMons() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ipv4AddrMons
}

// GetIpv4AddrMonsOk returns a tuple with the Ipv4AddrMons field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetIpv4AddrMonsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv4AddrMons, true
}

// SetIpv4AddrMons sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetIpv4AddrMons(v int32) {
	o.Ipv4AddrMons = v
}

// GetIpv6AddrMons returns the Ipv6AddrMons field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetIpv6AddrMons() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Ipv6AddrMons
}

// GetIpv6AddrMonsOk returns a tuple with the Ipv6AddrMons field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetIpv6AddrMonsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Ipv6AddrMons, true
}

// SetIpv6AddrMons sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetIpv6AddrMons(v int32) {
	o.Ipv6AddrMons = v
}

// GetMinMonRelease returns the MinMonRelease field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetMinMonRelease() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MinMonRelease
}

// GetMinMonReleaseOk returns a tuple with the MinMonRelease field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetMinMonReleaseOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MinMonRelease, true
}

// SetMinMonRelease sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetMinMonRelease(v int32) {
	o.MinMonRelease = v
}

// GetV1AddrMons returns the V1AddrMons field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetV1AddrMons() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.V1AddrMons
}

// GetV1AddrMonsOk returns a tuple with the V1AddrMons field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetV1AddrMonsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.V1AddrMons, true
}

// SetV1AddrMons sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetV1AddrMons(v int32) {
	o.V1AddrMons = v
}

// GetV2AddrMons returns the V2AddrMons field value
func (o *ApiTelemetryReportGet200ResponseReportMon) GetV2AddrMons() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.V2AddrMons
}

// GetV2AddrMonsOk returns a tuple with the V2AddrMons field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMon) GetV2AddrMonsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.V2AddrMons, true
}

// SetV2AddrMons sets field value
func (o *ApiTelemetryReportGet200ResponseReportMon) SetV2AddrMons(v int32) {
	o.V2AddrMons = v
}

func (o ApiTelemetryReportGet200ResponseReportMon) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTelemetryReportGet200ResponseReportMon) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["count"] = o.Count
	toSerialize["features"] = o.Features
	toSerialize["ipv4_addr_mons"] = o.Ipv4AddrMons
	toSerialize["ipv6_addr_mons"] = o.Ipv6AddrMons
	toSerialize["min_mon_release"] = o.MinMonRelease
	toSerialize["v1_addr_mons"] = o.V1AddrMons
	toSerialize["v2_addr_mons"] = o.V2AddrMons
	return toSerialize, nil
}

func (o *ApiTelemetryReportGet200ResponseReportMon) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"count",
		"features",
		"ipv4_addr_mons",
		"ipv6_addr_mons",
		"min_mon_release",
		"v1_addr_mons",
		"v2_addr_mons",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTelemetryReportGet200ResponseReportMon := _ApiTelemetryReportGet200ResponseReportMon{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTelemetryReportGet200ResponseReportMon)

	if err != nil {
		return err
	}

	*o = ApiTelemetryReportGet200ResponseReportMon(varApiTelemetryReportGet200ResponseReportMon)

	return err
}

type NullableApiTelemetryReportGet200ResponseReportMon struct {
	value *ApiTelemetryReportGet200ResponseReportMon
	isSet bool
}

func (v NullableApiTelemetryReportGet200ResponseReportMon) Get() *ApiTelemetryReportGet200ResponseReportMon {
	return v.value
}

func (v *NullableApiTelemetryReportGet200ResponseReportMon) Set(val *ApiTelemetryReportGet200ResponseReportMon) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTelemetryReportGet200ResponseReportMon) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTelemetryReportGet200ResponseReportMon) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTelemetryReportGet200ResponseReportMon(val *ApiTelemetryReportGet200ResponseReportMon) *NullableApiTelemetryReportGet200ResponseReportMon {
	return &NullableApiTelemetryReportGet200ResponseReportMon{value: val, isSet: true}
}

func (v NullableApiTelemetryReportGet200ResponseReportMon) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTelemetryReportGet200ResponseReportMon) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


