/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion{}

// ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion 
type ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion struct {
	// 
	CephVersion16003151Gf202994fcf int32 `json:"ceph version 16.0.0-3151-gf202994fcf"`
}

type _ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion

// NewApiTelemetryReportGet200ResponseReportMetadataMonCephVersion instantiates a new ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTelemetryReportGet200ResponseReportMetadataMonCephVersion(cephVersion16003151Gf202994fcf int32) *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion {
	this := ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion{}
	this.CephVersion16003151Gf202994fcf = cephVersion16003151Gf202994fcf
	return &this
}

// NewApiTelemetryReportGet200ResponseReportMetadataMonCephVersionWithDefaults instantiates a new ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTelemetryReportGet200ResponseReportMetadataMonCephVersionWithDefaults() *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion {
	this := ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion{}
	return &this
}

// GetCephVersion16003151Gf202994fcf returns the CephVersion16003151Gf202994fcf field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) GetCephVersion16003151Gf202994fcf() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CephVersion16003151Gf202994fcf
}

// GetCephVersion16003151Gf202994fcfOk returns a tuple with the CephVersion16003151Gf202994fcf field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) GetCephVersion16003151Gf202994fcfOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CephVersion16003151Gf202994fcf, true
}

// SetCephVersion16003151Gf202994fcf sets field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) SetCephVersion16003151Gf202994fcf(v int32) {
	o.CephVersion16003151Gf202994fcf = v
}

func (o ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["ceph version 16.0.0-3151-gf202994fcf"] = o.CephVersion16003151Gf202994fcf
	return toSerialize, nil
}

func (o *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"ceph version 16.0.0-3151-gf202994fcf",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTelemetryReportGet200ResponseReportMetadataMonCephVersion := _ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTelemetryReportGet200ResponseReportMetadataMonCephVersion)

	if err != nil {
		return err
	}

	*o = ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion(varApiTelemetryReportGet200ResponseReportMetadataMonCephVersion)

	return err
}

type NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion struct {
	value *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion
	isSet bool
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) Get() *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion {
	return v.value
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) Set(val *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion(val *ApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) *NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion {
	return &NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion{value: val, isSet: true}
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataMonCephVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


