/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
)

// checks if the ApiBlockMirroringPoolPoolNamePutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiBlockMirroringPoolPoolNamePutRequest{}

// ApiBlockMirroringPoolPoolNamePutRequest struct for ApiBlockMirroringPoolPoolNamePutRequest
type ApiBlockMirroringPoolPoolNamePutRequest struct {
	MirrorMode *string `json:"mirror_mode,omitempty"`
}

// NewApiBlockMirroringPoolPoolNamePutRequest instantiates a new ApiBlockMirroringPoolPoolNamePutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiBlockMirroringPoolPoolNamePutRequest() *ApiBlockMirroringPoolPoolNamePutRequest {
	this := ApiBlockMirroringPoolPoolNamePutRequest{}
	return &this
}

// NewApiBlockMirroringPoolPoolNamePutRequestWithDefaults instantiates a new ApiBlockMirroringPoolPoolNamePutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiBlockMirroringPoolPoolNamePutRequestWithDefaults() *ApiBlockMirroringPoolPoolNamePutRequest {
	this := ApiBlockMirroringPoolPoolNamePutRequest{}
	return &this
}

// GetMirrorMode returns the MirrorMode field value if set, zero value otherwise.
func (o *ApiBlockMirroringPoolPoolNamePutRequest) GetMirrorMode() string {
	if o == nil || IsNil(o.MirrorMode) {
		var ret string
		return ret
	}
	return *o.MirrorMode
}

// GetMirrorModeOk returns a tuple with the MirrorMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiBlockMirroringPoolPoolNamePutRequest) GetMirrorModeOk() (*string, bool) {
	if o == nil || IsNil(o.MirrorMode) {
		return nil, false
	}
	return o.MirrorMode, true
}

// HasMirrorMode returns a boolean if a field has been set.
func (o *ApiBlockMirroringPoolPoolNamePutRequest) HasMirrorMode() bool {
	if o != nil && !IsNil(o.MirrorMode) {
		return true
	}

	return false
}

// SetMirrorMode gets a reference to the given string and assigns it to the MirrorMode field.
func (o *ApiBlockMirroringPoolPoolNamePutRequest) SetMirrorMode(v string) {
	o.MirrorMode = &v
}

func (o ApiBlockMirroringPoolPoolNamePutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiBlockMirroringPoolPoolNamePutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MirrorMode) {
		toSerialize["mirror_mode"] = o.MirrorMode
	}
	return toSerialize, nil
}

type NullableApiBlockMirroringPoolPoolNamePutRequest struct {
	value *ApiBlockMirroringPoolPoolNamePutRequest
	isSet bool
}

func (v NullableApiBlockMirroringPoolPoolNamePutRequest) Get() *ApiBlockMirroringPoolPoolNamePutRequest {
	return v.value
}

func (v *NullableApiBlockMirroringPoolPoolNamePutRequest) Set(val *ApiBlockMirroringPoolPoolNamePutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiBlockMirroringPoolPoolNamePutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiBlockMirroringPoolPoolNamePutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiBlockMirroringPoolPoolNamePutRequest(val *ApiBlockMirroringPoolPoolNamePutRequest) *NullableApiBlockMirroringPoolPoolNamePutRequest {
	return &NullableApiBlockMirroringPoolPoolNamePutRequest{value: val, isSet: true}
}

func (v NullableApiBlockMirroringPoolPoolNamePutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiBlockMirroringPoolPoolNamePutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


