/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiCephfsFsIdQuotaPutRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiCephfsFsIdQuotaPutRequest{}

// ApiCephfsFsIdQuotaPutRequest struct for ApiCephfsFsIdQuotaPutRequest
type ApiCephfsFsIdQuotaPutRequest struct {
	MaxBytes *string `json:"max_bytes,omitempty"`
	MaxFiles *string `json:"max_files,omitempty"`
	Path string `json:"path"`
}

type _ApiCephfsFsIdQuotaPutRequest ApiCephfsFsIdQuotaPutRequest

// NewApiCephfsFsIdQuotaPutRequest instantiates a new ApiCephfsFsIdQuotaPutRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiCephfsFsIdQuotaPutRequest(path string) *ApiCephfsFsIdQuotaPutRequest {
	this := ApiCephfsFsIdQuotaPutRequest{}
	this.Path = path
	return &this
}

// NewApiCephfsFsIdQuotaPutRequestWithDefaults instantiates a new ApiCephfsFsIdQuotaPutRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiCephfsFsIdQuotaPutRequestWithDefaults() *ApiCephfsFsIdQuotaPutRequest {
	this := ApiCephfsFsIdQuotaPutRequest{}
	return &this
}

// GetMaxBytes returns the MaxBytes field value if set, zero value otherwise.
func (o *ApiCephfsFsIdQuotaPutRequest) GetMaxBytes() string {
	if o == nil || IsNil(o.MaxBytes) {
		var ret string
		return ret
	}
	return *o.MaxBytes
}

// GetMaxBytesOk returns a tuple with the MaxBytes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCephfsFsIdQuotaPutRequest) GetMaxBytesOk() (*string, bool) {
	if o == nil || IsNil(o.MaxBytes) {
		return nil, false
	}
	return o.MaxBytes, true
}

// HasMaxBytes returns a boolean if a field has been set.
func (o *ApiCephfsFsIdQuotaPutRequest) HasMaxBytes() bool {
	if o != nil && !IsNil(o.MaxBytes) {
		return true
	}

	return false
}

// SetMaxBytes gets a reference to the given string and assigns it to the MaxBytes field.
func (o *ApiCephfsFsIdQuotaPutRequest) SetMaxBytes(v string) {
	o.MaxBytes = &v
}

// GetMaxFiles returns the MaxFiles field value if set, zero value otherwise.
func (o *ApiCephfsFsIdQuotaPutRequest) GetMaxFiles() string {
	if o == nil || IsNil(o.MaxFiles) {
		var ret string
		return ret
	}
	return *o.MaxFiles
}

// GetMaxFilesOk returns a tuple with the MaxFiles field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiCephfsFsIdQuotaPutRequest) GetMaxFilesOk() (*string, bool) {
	if o == nil || IsNil(o.MaxFiles) {
		return nil, false
	}
	return o.MaxFiles, true
}

// HasMaxFiles returns a boolean if a field has been set.
func (o *ApiCephfsFsIdQuotaPutRequest) HasMaxFiles() bool {
	if o != nil && !IsNil(o.MaxFiles) {
		return true
	}

	return false
}

// SetMaxFiles gets a reference to the given string and assigns it to the MaxFiles field.
func (o *ApiCephfsFsIdQuotaPutRequest) SetMaxFiles(v string) {
	o.MaxFiles = &v
}

// GetPath returns the Path field value
func (o *ApiCephfsFsIdQuotaPutRequest) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *ApiCephfsFsIdQuotaPutRequest) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *ApiCephfsFsIdQuotaPutRequest) SetPath(v string) {
	o.Path = v
}

func (o ApiCephfsFsIdQuotaPutRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiCephfsFsIdQuotaPutRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.MaxBytes) {
		toSerialize["max_bytes"] = o.MaxBytes
	}
	if !IsNil(o.MaxFiles) {
		toSerialize["max_files"] = o.MaxFiles
	}
	toSerialize["path"] = o.Path
	return toSerialize, nil
}

func (o *ApiCephfsFsIdQuotaPutRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiCephfsFsIdQuotaPutRequest := _ApiCephfsFsIdQuotaPutRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiCephfsFsIdQuotaPutRequest)

	if err != nil {
		return err
	}

	*o = ApiCephfsFsIdQuotaPutRequest(varApiCephfsFsIdQuotaPutRequest)

	return err
}

type NullableApiCephfsFsIdQuotaPutRequest struct {
	value *ApiCephfsFsIdQuotaPutRequest
	isSet bool
}

func (v NullableApiCephfsFsIdQuotaPutRequest) Get() *ApiCephfsFsIdQuotaPutRequest {
	return v.value
}

func (v *NullableApiCephfsFsIdQuotaPutRequest) Set(val *ApiCephfsFsIdQuotaPutRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiCephfsFsIdQuotaPutRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiCephfsFsIdQuotaPutRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiCephfsFsIdQuotaPutRequest(val *ApiCephfsFsIdQuotaPutRequest) *NullableApiCephfsFsIdQuotaPutRequest {
	return &NullableApiCephfsFsIdQuotaPutRequest{value: val, isSet: true}
}

func (v NullableApiCephfsFsIdQuotaPutRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiCephfsFsIdQuotaPutRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


