/*
Ceph REST API

This is the official Ceph REST API

API version: v1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package ceph

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore{}

// ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore 
type ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore struct {
	// 
	Bluestore int32 `json:"bluestore"`
}

type _ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore

// NewApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore instantiates a new ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore(bluestore int32) *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore {
	this := ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore{}
	this.Bluestore = bluestore
	return &this
}

// NewApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstoreWithDefaults instantiates a new ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstoreWithDefaults() *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore {
	this := ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore{}
	return &this
}

// GetBluestore returns the Bluestore field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) GetBluestore() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Bluestore
}

// GetBluestoreOk returns a tuple with the Bluestore field value
// and a boolean to check if the value has been set.
func (o *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) GetBluestoreOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bluestore, true
}

// SetBluestore sets field value
func (o *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) SetBluestore(v int32) {
	o.Bluestore = v
}

func (o ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["bluestore"] = o.Bluestore
	return toSerialize, nil
}

func (o *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"bluestore",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore := _ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore)

	if err != nil {
		return err
	}

	*o = ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore(varApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore)

	return err
}

type NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore struct {
	value *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore
	isSet bool
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) Get() *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore {
	return v.value
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) Set(val *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) {
	v.value = val
	v.isSet = true
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) IsSet() bool {
	return v.isSet
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore(val *ApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) *NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore {
	return &NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore{value: val, isSet: true}
}

func (v NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiTelemetryReportGet200ResponseReportMetadataOsdOsdObjectstore) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


